let portfolioData = {
    "imagebaseurl":"https://techonoeticsclub.github.io/",
    "name": "Srinidhi Karnati",
    "home": "Home",
    "about": "About",
    "exp": "Experience",
    "edu": "Education",
    "skills": "Skills",
    "work": "My Work",
    "contact": "Contact",
    "role": "Responsive Frontend Developer",
    "aboutme": "I'm a Graduate student majored in Information Systems Management. With an undergrad background in Information Technology, I hold an expertise in Programming, Website Development, and Database Management. Majorly skilled in developing consistent, flexible and responsive Front End Web applications. ",
    "profSummary": "Professional Summary",
    "summary1": "Proficient and extensive experience of designing in HTML5, CSS3, JavaScript, jQuery, AngularJS, ReactJS and VueJS frameworks.",
    "summary2": "Designed web pages and front-end applications that meet business and user goals through a positive user experience.",
    "summary3": "Excelled under lead developer in requirements gathering and implementation in Agile environment.",
    "ProjectTitle1": "IT HelpDesk Schedule Management System",
    "ProjectDesc1": "A live project developed for Marist College, Information Technology Help Desk to improve the available scheduling system. The project proposed is a dynamic web application that provides a more optimized and automated version of the existed Timesheet schedule system",
    "TechDesc1": "Technologies: HTML5, CSS3, JavaScript, PHP, SQLite",
    "ProjectTitle2": "Library Mobile Application (SPA)",
    "ProjectDesc2": "A mobile application developed using Ionic 3, AngularJS, SASS with BEM naming. This single page mobile application provides a clean and responsive user interface that meets the user requirements",
    "TechDesc2": "Technologies: AngularJS, Ionic Framework 3, TypeScript, SQL Server, HTML5, CSS3, SASS, JavaScript, jQuery, AWS EC2",
    "ProjectTitle3": "Speech Enabled Library Management System",
    "ProjectDesc3": "A viable alternative to existing library management system, where users can interact with the system with their speech. Yates- Fisher's shuffle algorithm is used for password authentication. HTML 5 Speech recognition API works only for google chrome, hence users must use google chrome to access our system",
    "TechDesc3": "Technologies: Java, SQL Server, HTML5, CSS3, jQuery, HTML5 Speech Recognition API",
    "phpform": "PHP Contact Form",
    "phpformdesc": "A simple contact form built with Php, Bootstrap with front-end and back-end form validations",
    "smiles": "Beautiful Smiles",
    "smilesdesc": "A project built with HTML, CSS and JavaScript implementing dynamic DOM manipulation to show current time updates",
    "todo": "Todo App",
    "tododesc": "A simple ToDo app to add or delete items to the todo list. Built using Angular and Bootstrap",
    "phpformurl": "http://srinidhikarnati-com.stackstaging.com/Content/Php/form.php",
    "smilesurl": "http://srinidhikarnati-com.stackstaging.com/Content/coding-challenge/Code.html",
    "todourl": "https://codesandbox.io/s/1yvv2or0rj",
    "githuburl": "https://github.com/Srinidhi09",
    "linkedinurl": "https://www.linkedin.com/in/srinidhikarnati/",
    "instagramurl": "https://www.instagram.com/nidhi_karnati/",
    "facebookurl": "https://www.facebook.com/nidhikarnati",
  }
  
  export default portfolioData